### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"ykohleducation",
    "email":"ykohleducation@gmail.com",
    "password":"password123"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"ykohleducation@gmail.com",
    "password":"password123"
}

### index
GET http://localhost:3000/api/v1/index
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2MDMxMjM1fQ.5PqcY0euIclY7kbcg9HtsI8sjp265tidGtwCeqN1roI

### delete
DELETE http://localhost:3000/api/v1/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2MDMxMjM1fQ.5PqcY0euIclY7kbcg9HtsI8sjp265tidGtwCeqN1roI

### Request untuk reset password ###
POST http://localhost:3000/api/v1/reset
Content-Type: application/json

{
    "password": "password123",
    "newPassword": "newpassword123"
}


### whoami
GET http://localhost:3000/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2MDMxMjM1fQ.5PqcY0euIclY7kbcg9HtsI8sjp265tidGtwCeqN1roI
